###

GET http://localhost:6969/criartabelausuario


###


POST https://render-db-uiqc.onrender.com/adicionarusuario
Content-Type: application/json

{
    "nome": "renato",
    "senha": "123456",
    "email": "renatofrassa09@gmail.com"
}